[package]
name = "rust-skrivetest"
version = "1.0.0"
edition = "2024"
repository = "https://github.com/isakbh/rust-skrivetest"

[dependencies]
chrono = "0.4.41"
rand = "0.9.2"
simple-stopwatch = "0.1.4"
whoami = "1.6.1"
